import type { Metadata } from "next";
import "./globals.css";

import { cn } from "-/lib/utils";
import { Inter } from "next/font/google";

const fontSans = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fontSans.className, "antialiased")}>{children}</body>
    </html>
  );
}
